#!/usr/bin/env python3
"""
Local server for The Dev Dispatch.
- Serves dev-dispatch.html and assets from this directory.
- GET /api/usage  -> live Claude usage (same endpoint Claude Code's /usage uses),
  pulling the OAuth token from the macOS Keychain. Cached 60s to respect the
  endpoint's aggressive rate limiting.

Run:  python3 usage-server.py   then open  http://localhost:8787/dev-dispatch.html
"""
import datetime
import glob
import http.server
import json
import os
import re
import shlex
import subprocess
import threading
import time
import urllib.request

PORT = 8787
DIR = os.path.dirname(os.path.abspath(__file__))
# All persisted dashboard state lives in one folder beside this script (gitignored,
# never published). Override with DISPATCH_STATE_DIR.
STATE_DIR = os.environ.get("DISPATCH_STATE_DIR", os.path.join(DIR, "state"))
os.makedirs(STATE_DIR, exist_ok=True)
USAGE_URL = "https://api.anthropic.com/api/oauth/usage"
# Root folder whose Claude Code sessions this dashboard surfaces.
# Override with DISPATCH_ROOT; defaults to ~/MyProjects.
MP = os.environ.get("DISPATCH_ROOT", os.path.expanduser("~/MyProjects")).rstrip("/")
# Claude Code stores each project's logs under ~/.claude/projects/<path-with-slashes-as-dashes>.
SESS_DIR = os.path.join(os.path.expanduser("~/.claude/projects"), MP.replace("/", "-"))
_cache = {"at": 0, "data": None}
_ctx_cache = {"at": 0, "data": None}
CACHE_TTL = 60  # seconds

# ---------- "read" markers: sessionId -> last-activity ts acknowledged ----------
READ_FILE = os.path.join(STATE_DIR, "read-markers.json")

# ---------- AI recaps: one-sentence "what & where it left off" per session ----------
# Generated via `claude -p` (the same Claude Code login your sessions use), cached on
# disk, and refreshed by a background worker. Only sessions that CHANGED since their
# last recap are regenerated, so finished sessions are summarized once and never again.
RECAP_PATH = os.path.join(STATE_DIR, "recaps.json")
RECAP_MODEL = "claude-haiku-4-5"
RECAP_INTERVAL = int(os.environ.get("RECAP_INTERVAL", "300"))  # worker loop, seconds
RECAP_CONCURRENCY = int(os.environ.get("RECAP_CONCURRENCY", "3"))

# ---------- the "Where am I right now" refocus board ----------
# A subject = one topic (the existing grouping). Each SESSION in it is an "issue" with
# its own structured card: a short label / status / next action / blocker. Generated by
# the same `claude -p` engine, cached on disk, regenerated only when that session changes.
ISSUECARD_PATH = os.path.join(STATE_DIR, "issuecards.json")
ARCHIVE_PATH = os.path.join(STATE_DIR, "archived.json")
CLOSED_PATH = os.path.join(STATE_DIR, "closed.json")  # sessions you closed (greyed, status "closed")
# Manual topic edits laid over the automatic grouping: rename a topic, delete/merge one
# (folding its sessions into another), or move a session to a different topic. Persisted so
# your organization survives restarts and shows on both dashboards.
TOPICS_PATH = os.path.join(STATE_DIR, "topics.json")
# Per-session flags set from the batch (multi-select) actions: "archived" (parked & greyed,
# hidden from the focus board) and "deleted" (soft-deleted — hidden from BOTH dashboards but
# fully recoverable from the Trash; the session's .jsonl log on disk is NEVER touched).
SESSION_FLAGS_PATH = os.path.join(STATE_DIR, "session-flags.json")
FOCUS_TOPN = int(os.environ.get("FOCUS_TOPN", "3"))         # subjects (topics) to show
FOCUS_POOL = int(os.environ.get("FOCUS_POOL", "5"))         # subjects to keep cards warm for
FOCUS_ISSUES = int(os.environ.get("FOCUS_ISSUES", "6"))     # issues (sessions) per subject
STALE_DAYS = int(os.environ.get("STALE_DAYS", "7"))         # drop sessions untouched this long
DONE_KEEP_DAYS = int(os.environ.get("DONE_KEEP_DAYS", "7"))  # done sessions vanish this long after

# Per-session context gauge. Sessions run different model windows (200k standard, or the
# 1M beta), so we infer the window from the session's own peak usage, then subtract the
# reserve Claude Code holds back for output — matching the terminal's "% context used".
# Calibrated to a real session: 155k tokens shown as 86% used -> ~180k effective (200k-20k).
CTX_RESERVE = int(os.environ.get("CTX_RESERVE", "20000"))    # output/headroom reserve


def _ctx_window(peak_tokens):
    """Effective usable context for this session = its model window minus the reserve."""
    model_window = 200_000 if (peak_tokens or 0) <= 200_000 else 1_000_000
    return max(1, model_window - CTX_RESERVE)


def _load_read():
    try:
        with open(READ_FILE) as fh:
            d = json.load(fh)
            return d if isinstance(d, dict) else {}
    except Exception:
        return {}


def _save_read(d):
    tmp = READ_FILE + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(d, fh, indent=2, sort_keys=True)
    os.replace(tmp, READ_FILE)


def _session_state(s, marks):
    """new = never acknowledged, updated = grew since last read, read = current."""
    mk = marks.get(s["id"])
    if mk is None:
        return "new"
    return "updated" if s["end"] > mk else "read"


def _apply_read_state(ctx):
    """Overlay read/unread state fresh on each request (outside the context cache,
    so 'mark read' reflects immediately)."""
    marks = _load_read()
    for s in ctx.get("sessions", []):
        s["state"] = _session_state(s, marks)
    for tp in ctx.get("topics", []):
        unread = 0
        for s in tp["sessions"]:
            s["state"] = _session_state(s, marks)
            if s["state"] != "read":
                unread += 1
        tp["unreadCount"] = unread
    return ctx


# ---------- real context from Claude Code session logs ----------
def _msg_text(msg):
    c = msg.get("content")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        for p in c:
            if isinstance(p, dict) and p.get("type") == "text":
                return p["text"]
    return ""


def _proj_of(cwd):
    """(name, label, is_root) from a session cwd."""
    if not cwd or not cwd.startswith(MP):
        return None
    rest = cwd[len(MP):].strip("/")
    if rest == "":
        return ("MyProjects", "root", True)
    parts = rest.split("/")
    label = parts[-1] if "worktrees" in parts else parts[0]
    return (parts[0], label, False)


_EDIT_TOOLS = {"Edit", "Write", "MultiEdit", "NotebookEdit"}


def _ctx_tokens(usage):
    """Total prompt tokens for one assistant turn = how full the context was at that point."""
    if not usage:
        return 0
    return (usage.get("input_tokens", 0)
            + usage.get("cache_creation_input_tokens", 0)
            + usage.get("cache_read_input_tokens", 0))


def _scan_session(path):
    first_user = last_user = summary = cwd = branch = ts0 = ts1 = None
    n = 0
    edited = {}  # file_path -> edit count (signal for grouping repo-less sessions)
    ctx_last = ctx_peak = 0  # context-window occupancy (tokens) — current & peak
    with open(path, errors="ignore") as fh:
        for line in fh:
            try:
                r = json.loads(line)
            except Exception:
                continue
            if r.get("type") == "summary":
                summary = r.get("summary")
            if r.get("cwd"):
                cwd = r["cwd"]
            if r.get("gitBranch"):
                branch = r["gitBranch"]
            if r.get("timestamp"):
                ts0 = ts0 or r["timestamp"]
                ts1 = r["timestamp"]
            if r.get("type") == "user" and not r.get("isMeta"):
                t = _msg_text(r.get("message", {})).strip().replace("\n", " ")
                if t and not t.startswith("<") and not t.startswith("Caveat"):
                    if first_user is None:
                        first_user = t
                    last_user = t
                    n += 1
            elif r.get("type") == "assistant":
                msg = r.get("message", {})
                tok = _ctx_tokens(msg.get("usage"))
                if tok:
                    ctx_last = tok  # last turn = current occupancy
                    ctx_peak = max(ctx_peak, tok)
                for part in (msg.get("content") or []):
                    if isinstance(part, dict) and part.get("type") == "tool_use" \
                            and part.get("name") in _EDIT_TOOLS:
                        inp = part.get("input") or {}
                        fp = inp.get("file_path") or inp.get("notebook_path")
                        if fp:
                            edited[fp] = edited.get(fp, 0) + 1
    return dict(cwd=cwd, branch=branch, ts0=ts0, ts1=ts1, n=n,
                summary=summary, first=first_user, last=last_user, edited=edited,
                ctxTokens=ctx_last, ctxPeak=ctx_peak)


_STOP = set((
    "the a an and or of to for in on at with my our your you i we is are be this "
    "that it im just need help want make please can get got use using feature work "
    "working file files code change changes add added like would could should do done "
    "from into out about all some more last first next new old how what why when"
).split())


def _norm_feature(feat):
    """Normalize a worktree/branch name so variants collapse to one topic."""
    f = feat.lower()
    f = re.sub(r"\d{4}[-_]?\d{2}[-_]?\d{2}", "", f)               # dates
    f = re.sub(r"[-_](squashed|copy|v\d+|final|new|old|wip|tmp|temp|2|3)\b", "", f)
    f = re.sub(r"^(feature|feat|fix|chore|wip)[-_/]?", "", f)     # branch prefixes
    f = re.sub(r"[-_/]+", " ", f).strip()
    return f or feat.lower()


def _keywords(text):
    toks = re.findall(r"[a-zA-Z][a-zA-Z0-9_-]{3,}", (text or "").lower())
    return {t for t in toks if t not in _STOP}


def _rel_parts(cwd):
    if cwd and cwd.startswith(MP):
        rel = cwd[len(MP):].strip("/")
        return [p for p in rel.split("/") if p]
    return []


_MP_PATH_RE = re.compile(re.escape(MP) + r"/([A-Za-z0-9._\-]+(?:/[A-Za-z0-9._\-]+)*)")


def _repo_feat_from_parts(parts):
    """(repo, normalized-feature|None) from MyProjects-relative path parts."""
    repo = parts[0]
    feat = None
    if "worktrees" in parts:
        i = parts.index("worktrees")
        feat = parts[i + 1] if len(parts) > i + 1 else None
    elif len(parts) > 1:
        feat = parts[-1]
    return repo, (_norm_feature(feat) if feat else None)


def _pick_repo_feat(parts_iter):
    """Most-frequent (repo, feature|None) over an iterable of (path-parts, weight).
    Only worktree paths contribute a feature, so stray file refs collapse to the repo."""
    counts = {}
    feat_of = {}
    for parts, w in parts_iter:
        if not parts:
            continue
        repo = parts[0]
        counts[repo] = counts.get(repo, 0) + w
        if "worktrees" in parts and repo not in feat_of:
            i = parts.index("worktrees")
            if len(parts) > i + 1:
                feat_of[repo] = _norm_feature(parts[i + 1])
    if not counts:
        return None
    repo = max(counts, key=lambda r: counts[r])
    return repo, feat_of.get(repo)


def _referenced_repo_feat(text):
    """(repo, feature|None) from /MyProjects/... paths mentioned in free text."""
    return _pick_repo_feat(
        ([p for p in m.group(1).split("/") if p], 1)
        for m in _MP_PATH_RE.finditer(text or "")
    )


def _edited_repo_feat(edited):
    """(repo, feature|None) from the paths of files actually edited — ground truth of
    which worktree the work happened in. Bare root-level files are ignored."""
    def gen():
        for fp, c in (edited or {}).items():
            if not fp.startswith(MP + "/"):
                continue
            parts = [p for p in fp[len(MP) + 1:].split("/") if p]
            if len(parts) >= 2:  # file inside a repo, not a bare root-level file
                yield parts, c
    return _pick_repo_feat(gen())


def _set_repo_topic(s, repo, featn, src):
    s["_key"] = "repo:%s/%s" % (repo, featn or "")
    s["_title"] = repo + (" · " + featn if featn else "")
    s["_src"] = src


def _assign_topics(sessions):
    """Resolve each session to a topic via the fallback chain:
       cwd repo+feature  ->  repo/path referenced in prompt  ->
       shared edited files  ->  misc."""
    repoless = []
    for s in sessions:
        # --- tier 1: cwd is inside a project dir/worktree ---
        parts = _rel_parts(s["cwd"])
        if parts:
            repo, featn = _repo_feat_from_parts(parts)
            _set_repo_topic(s, repo, featn, "repo")
            continue
        # --- tier 2: work outranks talk -> the worktree you actually edited in ---
        ref = _edited_repo_feat(s["edited"])
        if ref:
            _set_repo_topic(s, ref[0], ref[1], "edits")
            continue
        # root-level edits only -> let the shared-files pass cluster them
        if s["edited"]:
            repoless.append(s)
            continue
        # --- tier 3: no edits (pure read/explore) -> topic by referenced path ---
        text = " ".join(t for t in (s.get("prompt"), s.get("lastPrompt"),
                                    s.get("summary")) if t)
        ref = _referenced_repo_feat(text)
        if ref:
            _set_repo_topic(s, ref[0], ref[1], "path")
        else:
            repoless.append(s)

    # --- tier 3: union-find over remaining root sessions, SHARED FILES ONLY ---
    # (no keyword edges — they transitively chained unrelated sessions into one blob)
    parent = list(range(len(repoless)))

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    files_sig = [set(s["edited"].keys()) for s in repoless]
    for i in range(len(repoless)):
        for j in range(i + 1, len(repoless)):
            if files_sig[i] & files_sig[j]:
                parent[find(i)] = find(j)

    comps = {}
    for i in range(len(repoless)):
        comps.setdefault(find(i), []).append(i)

    for members in comps.values():
        files = {}
        for i in members:
            for fp, c in repoless[i]["edited"].items():
                b = os.path.basename(fp)
                files[b] = files.get(b, 0) + c
        if files:
            top = sorted(files, key=lambda x: -files[x])[:2]
            title = " + ".join(top)
            key = "files:" + "|".join(sorted(top))
            src = "files"
        else:
            title, key, src = "Misc / one-offs", "misc", "misc"
        for i in members:
            repoless[i]["_key"] = key
            repoless[i]["_title"] = title
            repoless[i]["_src"] = src
    return sessions


# ----------------------------- manual topic overrides -----------------------------
# topics.json shape:
#   {"renames": {key: title}, "merges": {srcKey: dstKey}, "moves": {sessionId: key}}
_KEY_RE = re.compile(
    r"^(repo:[A-Za-z0-9 ._+/|-]*|files:[A-Za-z0-9 ._+|-]*|custom:[A-Za-z0-9]+|misc)$")
_UUID_RE = re.compile(r"[0-9a-fA-F-]{36}")


def _topics_load():
    try:
        with open(TOPICS_PATH) as fh:
            d = json.load(fh)
            return d if isinstance(d, dict) else {}
    except Exception:
        return {}


def _topics_save(ov):
    tmp = TOPICS_PATH + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(ov, fh, indent=2, sort_keys=True)
    os.replace(tmp, TOPICS_PATH)


def _derive_title(key):
    """Best-effort human title for a topic key with no session structurally in it."""
    if key.startswith("repo:"):
        repo, _, feat = key[5:].partition("/")
        return repo + (" · " + feat if feat else "")
    if key.startswith("files:"):
        return key[6:].replace("|", " + ")
    return key


def _apply_topic_overrides(sessions):
    """Overlay the user's manual edits (rename / delete-merge / move) on the structural
    grouping. Each session already carries _key/_title from _assign_topics."""
    ov = _topics_load()
    renames, merges, moves = (ov.get("renames") or {}, ov.get("merges") or {},
                              ov.get("moves") or {})
    if not (renames or merges or moves):
        return
    nat_title = {s["_key"]: s["_title"] for s in sessions}  # structural titles, pre-edit

    def resolve(k):  # follow the delete/merge chain (cycle-guarded)
        seen = set()
        while k in merges and k not in seen:
            seen.add(k)
            k = merges[k]
        return k

    for s in sessions:
        k = resolve(moves.get(s["id"]) or s["_key"])
        s["_key"] = k
        s["_title"] = renames.get(k) or nat_title.get(k) or _derive_title(k)


def _valid_key(k):
    return isinstance(k, str) and bool(_KEY_RE.fullmatch(k))


def _clean_title(t):
    return (t or "").strip()[:80]


def _topic_action(action, body):
    """Apply and persist one topic edit. Raises ValueError on bad input."""
    ov = _topics_load()
    renames = ov.setdefault("renames", {})
    merges = ov.setdefault("merges", {})
    moves = ov.setdefault("moves", {})

    if action == "rename":
        key = body.get("key", "")
        if not _valid_key(key):
            raise ValueError("invalid topic key")
        title = _clean_title(body.get("title"))
        if title:
            renames[key] = title
        else:
            renames.pop(key, None)  # empty -> revert to the automatic name
        _topics_save(ov)
        return {"key": key, "title": title}

    if action in ("delete", "merge"):
        key, target = body.get("key", ""), body.get("target", "")
        if not _valid_key(key) or not _valid_key(target):
            raise ValueError("invalid topic key")
        if target == key:
            raise ValueError("cannot send a topic into itself")
        # refuse to create a merge loop (target chaining back to key)
        t, seen = target, set()
        while t in merges:
            if t == key or t in seen:
                raise ValueError("that would create a topic loop")
            seen.add(t)
            t = merges[t]
        if t == key:
            raise ValueError("that would create a topic loop")
        tt = _clean_title(body.get("targetTitle"))
        if tt:
            renames[target] = tt  # naming a brand-new destination topic
        merges[key] = target
        for sid, k in list(moves.items()):  # sessions moved into the deleted topic follow
            if k == key:
                moves[sid] = target
        renames.pop(key, None)  # the deleted topic's own custom name is gone
        _topics_save(ov)
        return {"key": key, "target": target}

    if action == "move":
        sid = body.get("session", "")
        if not _UUID_RE.fullmatch(sid or ""):
            raise ValueError("invalid session id")
        key = body.get("key", "")
        if not key:
            moves.pop(sid, None)  # clear the override -> back to the automatic topic
        else:
            if not _valid_key(key):
                raise ValueError("invalid topic key")
            tt = _clean_title(body.get("title"))
            if tt:
                renames[key] = tt
            moves[sid] = key
        _topics_save(ov)
        return {"session": sid, "key": key}

    raise ValueError("unknown topic action")


# ----------------------------- per-session batch flags -----------------------------
def _sflags_load():
    try:
        with open(SESSION_FLAGS_PATH) as fh:
            d = json.load(fh)
            return d if isinstance(d, dict) else {}
    except Exception:
        return {}


def _sflags_save(d):
    tmp = SESSION_FLAGS_PATH + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(d, fh, indent=2, sort_keys=True)
    os.replace(tmp, SESSION_FLAGS_PATH)


def _set_session_flag(sids, flag, on):
    """Set/clear one flag ("archived" | "deleted") on a batch of session ids."""
    d = _sflags_load()
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    for sid in sids:
        rec = d.get(sid) or {}
        if on:
            rec[flag] = now
        else:
            rec.pop(flag, None)
        if rec:
            d[sid] = rec
        else:
            d.pop(sid, None)
    _sflags_save(d)


def _move_sessions(sids, key, title):
    """Batch-move sessions to a topic (key empty -> revert each to its automatic topic)."""
    ov = _topics_load()
    moves = ov.setdefault("moves", {})
    renames = ov.setdefault("renames", {})
    if not key:
        for sid in sids:
            moves.pop(sid, None)
    else:
        if not _valid_key(key):
            raise ValueError("invalid topic key")
        tt = _clean_title(title)
        if tt:
            renames[key] = tt
        for sid in sids:
            moves[sid] = key
    _topics_save(ov)


def _sessions_action(action, body):
    """Apply and persist a batch action over selected sessions. Returns a small summary."""
    sids = [s for s in (body.get("sessions") or []) if _UUID_RE.fullmatch(s or "")]
    if not sids:
        raise ValueError("no valid sessions")
    if action == "move":
        _move_sessions(sids, body.get("key", ""), body.get("title"))
    elif action in ("archive", "unarchive"):
        _set_session_flag(sids, "archived", action == "archive")
    elif action in ("delete", "undelete"):
        _set_session_flag(sids, "deleted", action == "delete")
    else:
        raise ValueError("unknown session action")
    return {"action": action, "count": len(sids)}


def _trash_list():
    """Soft-deleted sessions, for the Trash/restore view. Reads each one's log only to
    recover a label — the logs themselves are never modified."""
    flags = _sflags_load()
    out = []
    for sid, rec in flags.items():
        if not rec.get("deleted"):
            continue
        path = os.path.join(SESS_DIR, sid + ".jsonl")
        prompt, project = "", ""
        if os.path.exists(path):
            s = _scan_session(path)
            prompt = (s.get("first") or "")[:120]
            pj = _proj_of(s.get("cwd"))
            project = pj[0] if pj else ""
        out.append({"id": sid, "prompt": prompt, "project": project,
                    "deletedAt": rec.get("deleted")})
    out.sort(key=lambda x: x.get("deletedAt") or "", reverse=True)
    return {"deleted": out, "count": len(out)}


def _dur_min(a, b):
    if not a or not b:
        return 0
    d = datetime.datetime.fromisoformat(b.replace("Z", "+00:00")) - \
        datetime.datetime.fromisoformat(a.replace("Z", "+00:00"))
    return max(0, round(d.total_seconds() / 60))


# ----------------------------- AI recaps -----------------------------
def _recap_load():
    try:
        with open(RECAP_PATH) as fh:
            return json.load(fh)
    except Exception:
        return {}


def _recap_save(d):
    tmp = RECAP_PATH + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(d, fh)
    os.replace(tmp, RECAP_PATH)


def _session_fp(n, ts1):
    """Fingerprint of a session's state — changes only when the session changes."""
    return f"{n}:{ts1}"


def _recap_prompts(path):
    """Collect the user prompts from a session log, for feeding to the recap model."""
    out = []
    with open(path, errors="ignore") as fh:
        for line in fh:
            try:
                r = json.loads(line)
            except Exception:
                continue
            if r.get("type") == "user" and not r.get("isMeta"):
                t = _msg_text(r.get("message", {})).strip().replace("\n", " ")
                if t and not t.startswith("<") and not t.startswith("Caveat"):
                    out.append(t[:300])
    return out


def _gen_recap(project, prompts, files, summary):
    """One-sentence recap via `claude -p` (same login the sessions use). None on failure."""
    sel = prompts[:4] + (prompts[-3:] if len(prompts) > 4 else [])
    parts = [
        "Write a single-sentence recap (max 22 words) of this coding session for a "
        "developer's dashboard. Say what was worked on and where it left off. Be specific "
        "and concrete. Output ONLY the sentence — no preamble, no quotes.\n",
        f"Project: {project}",
    ]
    if summary:
        parts.append(f"Auto-summary: {summary}")
    if files:
        parts.append("Files touched: " + ", ".join(os.path.basename(f) for f in files[:8]))
    parts.append("User prompts (chronological):\n" + "\n".join(f"- {p}" for p in sel))
    prompt = "\n".join(parts)
    try:
        res = subprocess.run(
            ["claude", "-p", "--model", RECAP_MODEL, prompt],
            capture_output=True, text=True, timeout=90,
        )
        txt = (res.stdout or "").strip().strip('"')
        return txt or None
    except Exception:
        return None


def _recap_refresh():
    """Generate recaps for sessions that are new or have changed since last time."""
    files = sorted(glob.glob(os.path.join(SESS_DIR, "*.jsonl")),
                   key=os.path.getmtime, reverse=True)[:500]
    cache = _recap_load()
    todo = []
    for f in files:
        s = _scan_session(f)
        pj = _proj_of(s["cwd"])
        if not pj or not s["ts0"] or s["n"] == 0:
            continue
        sid = os.path.basename(f)[:-6]
        fp = _session_fp(s["n"], s["ts1"])
        if cache.get(sid, {}).get("fp") != fp:
            todo.append((sid, f, s, pj[0], fp))
    if not todo:
        return 0

    def work(item):
        sid, f, s, project, fp = item
        recap = _gen_recap(project, _recap_prompts(f), list(s["edited"].keys()), s.get("summary"))
        return sid, recap, fp

    done = 0
    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=RECAP_CONCURRENCY) as ex:
        for sid, recap, fp in ex.map(work, todo):
            if recap:
                cache[sid] = {"recap": recap, "fp": fp,
                              "at": datetime.datetime.now(datetime.timezone.utc).isoformat()}
                _recap_save(cache)  # incremental, so the menu fills in progressively
                done += 1
    return done


# ----------------------------- issue cards (per session) -----------------------------
def _issuecard_load():
    try:
        with open(ISSUECARD_PATH) as fh:
            return json.load(fh)
    except Exception:
        return {}


def _issuecard_save(d):
    tmp = ISSUECARD_PATH + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(d, fh)
    os.replace(tmp, ISSUECARD_PATH)


def _parse_card_json(text):
    """Pull a JSON object out of the model's reply, tolerating stray prose/fences."""
    t = (text or "").strip()
    if t.startswith("```"):
        t = re.sub(r"^```[a-zA-Z]*\n?|\n?```$", "", t).strip()
    i, j = t.find("{"), t.rfind("}")
    if i == -1 or j == -1:
        return None
    try:
        return json.loads(t[i:j + 1])
    except Exception:
        return None


def _gen_issuecard(project, label, prompts, summary, recap):
    """Structured card (issue / status / next / blocked) for ONE session via `claude -p`."""
    sel = prompts[:3] + (prompts[-3:] if len(prompts) > 3 else [])
    prompt = (
        "You summarize ONE coding session as a single 'issue' on a developer's ADHD "
        "re-focus board. The developer forgets state when focus drops, so be concrete and "
        "name the real thing. Output ONLY a JSON object (no markdown, no prose) with EXACTLY:\n"
        '  "issue": a short label for what this session is about (<=7 words)\n'
        '  "status": one of "in_progress" | "blocked" | "winding_down" | "done"\n'
        '  "next": ONE concrete next action for this session (<=12 words, imperative)\n'
        '  "blocked": a short open problem/blocker, or "" if none\n\n'
        f"Project: {project}" + (f" / {label}" if label and label != project else "") + "\n"
        + (f"Auto-summary: {summary}\n" if summary else "")
        + (f"Earlier recap: {recap}\n" if recap else "")
        + "User prompts (chronological):\n" + "\n".join(f"- {p}" for p in sel)
    )
    try:
        res = subprocess.run(
            ["claude", "-p", "--model", RECAP_MODEL, prompt],
            capture_output=True, text=True, timeout=120,
        )
        card = _parse_card_json(res.stdout)
        if not card or "next" not in card:
            return None
        return {
            "issue": card.get("issue") or "",
            "status": card.get("status") or "in_progress",
            "next": card.get("next") or "",
            "blocked": card.get("blocked") or "",
        }
    except Exception:
        return None


def _focus_sessions():
    """The (sessionId -> session dict) set we keep issue-cards warm for: the issues inside
    the top FOCUS_POOL subjects, capped to FOCUS_ISSUES sessions each."""
    ctx = _build_context()
    wanted = {}
    for t in (ctx.get("topics") or [])[:FOCUS_POOL]:
        for s in t["sessions"][:FOCUS_ISSUES]:
            wanted[s["id"]] = s
    return wanted


def _issuecard_refresh():
    """Generate/refresh issue cards for the sessions visible on the focus board."""
    wanted = _focus_sessions()
    cache = _issuecard_load()
    todo = [s for sid, s in wanted.items()
            if cache.get(sid, {}).get("fp") != _session_fp(s["msgs"], s["end"])]
    if not todo:
        return 0

    def work(s):
        path = os.path.join(SESS_DIR, s["id"] + ".jsonl")
        prompts = _recap_prompts(path) if os.path.exists(path) else [s.get("prompt", "")]
        card = _gen_issuecard(s.get("project", ""), s.get("label", ""),
                              prompts, s.get("summary"), s.get("recap"))
        return s["id"], card, _session_fp(s["msgs"], s["end"])

    done = 0
    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=RECAP_CONCURRENCY) as ex:
        for sid, card, fp in ex.map(work, todo):
            if card:
                cache[sid] = {"card": card, "fp": fp,
                              "at": datetime.datetime.now(datetime.timezone.utc).isoformat()}
                _issuecard_save(cache)
                done += 1
    return done


_SUBJECT_RANK = {"blocked": 0, "in_progress": 1, "winding_down": 2, "done": 3, "closed": 4}


def _subject_status(issues):
    """Roll up a subject's status from its issues: blocked > in_progress > winding_down > done."""
    statuses = [i["card"].get("status") or "in_progress" for i in issues if i.get("card")]
    if not statuses:
        return "in_progress"
    return min(statuses, key=lambda s: _SUBJECT_RANK.get(s, 1))


def _closed_load():
    try:
        with open(CLOSED_PATH) as fh:
            return json.load(fh)
    except Exception:
        return {}


def _closed_save(d):
    tmp = CLOSED_PATH + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(d, fh, indent=2)
    os.replace(tmp, CLOSED_PATH)


def set_closed(sid, undo):
    """Persist a session 'close' click (or reopen). Returns the new closed state."""
    closed = _closed_load()
    if undo:
        closed.pop(sid, None)
    else:
        closed[sid] = {"closedAt": datetime.datetime.now(datetime.timezone.utc).isoformat()}
    _closed_save(closed)
    return not undo


def _archive_load():
    try:
        with open(ARCHIVE_PATH) as fh:
            return json.load(fh)
    except Exception:
        return {}


def _archive_save(d):
    tmp = ARCHIVE_PATH + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(d, fh, indent=2)
    os.replace(tmp, ARCHIVE_PATH)


def _subject_fp(topic):
    """Fingerprint of a subject — changes when ANY of its sessions gains activity, so an
    archived subject auto-revives the moment you touch it again."""
    parts = sorted(f"{s['id']}:{s.get('msgs')}:{s.get('end')}" for s in topic["sessions"])
    return str(hash("|".join(parts)))


def set_archived(subject_key, undo, topics):
    """Persist an archive/undo action. Returns the new archived state for that key."""
    arch = _archive_load()
    if undo:
        arch.pop(subject_key, None)
    else:
        t = next((x for x in topics if x["id"] == subject_key), None)
        arch[subject_key] = {
            "archivedAt": datetime.datetime.now(datetime.timezone.utc).isoformat(),
            "fp": _subject_fp(t) if t else None,
        }
    _archive_save(arch)
    return not undo


def _archived_topic_ids(topics):
    """The set of topic ids currently archived, auto-reviving (and persisting the revive of)
    any whose sessions gained activity since you archived them."""
    arch = _archive_load()
    if not arch:
        return set()
    by_id = {t["id"]: t for t in topics}
    out, changed = set(), False
    for tid, a in list(arch.items()):
        t = by_id.get(tid)
        if t is None:
            continue  # topic not in this scan (empty/stale) — leave the record untouched
        if a.get("fp") == _subject_fp(t):
            out.add(tid)            # still archived — untouched since
        else:
            arch.pop(tid, None)     # new activity -> auto-revive
            changed = True
    if changed:
        _archive_save(arch)
    return out


def _eligible_subjects(topics):
    """Filter out stale and archived subjects (auto-reviving any that got new activity)."""
    archived_ids = _archived_topic_ids(topics)
    stale_cut = (datetime.datetime.now(datetime.timezone.utc)
                 - datetime.timedelta(days=STALE_DAYS)).isoformat()
    eligible, archived_now = [], []
    for t in topics:
        if t["lastActivity"] < stale_cut:
            continue  # staleness gate (objective; nothing saved)
        if t["id"] in archived_ids:
            archived_now.append({"id": t["id"], "title": t["title"],
                                 "lastActivity": t["lastActivity"]})
            continue  # still archived — you haven't touched it since
        eligible.append(t)
    return eligible, archived_now


def _build_focus():
    """The refocus board: top subjects (topics), each with its issues (sessions) as cards."""
    ctx = _build_context()
    topics = ctx.get("topics") or []
    cache = _issuecard_load()
    eligible, archived_now = _eligible_subjects(topics)
    closed_map = _closed_load()
    done_cut = (datetime.datetime.now(datetime.timezone.utc)
                - datetime.timedelta(days=DONE_KEEP_DAYS)).isoformat()

    def _keep(s):
        if s.get("archived"):
            return False  # parked individually -> off the "right now" board
        # done sessions vanish a week after they were marked done
        if not s.get("closed"):
            return True
        ca = (closed_map.get(s["id"]) or {}).get("closedAt")
        return not ca or ca >= done_cut

    out = []
    for t in eligible[:FOCUS_TOPN]:
        kept = [s for s in t["sessions"] if _keep(s)]
        kept.sort(key=lambda s: 1 if s.get("closed") else 0)  # done sink to the bottom
        sessions = kept[:FOCUS_ISSUES]
        if not sessions:
            continue  # every session here is done and has aged out
        issues = []
        for s in sessions:
            card = (cache.get(s["id"]) or {}).get("card")
            is_closed = bool(s.get("closed"))
            if is_closed and card:
                card = {**card, "status": "closed"}  # closed overrides the AI status
            issues.append({
                "id": s["id"],
                "project": s.get("project", ""),
                "label": s.get("label", ""),
                "msgs": s.get("msgs"),
                "start": s.get("start"),   # when the session was created
                "end": s.get("end"),       # last prompt sent
                "recap": s.get("recap"),
                "ctxTokens": s.get("ctxTokens"),
                "ctxPct": s.get("ctxPct"),
                "ctxWindow": s.get("ctxWindow"),
                "closed": is_closed,
                "card": card,
            })
        recent = sessions[0] if sessions else {}
        out.append({
            "id": t["id"],
            "title": t["title"],
            "project": recent.get("project", ""),
            "source": t.get("source"),
            "sessionCount": t["sessionCount"],
            "issueCount": len(issues),
            "lastActivity": t["lastActivity"],
            "resumeSessionId": recent.get("id"),
            "status": _subject_status(issues),
            "issues": issues,
        })
    return {
        "generated_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "subjects": out,
        "totalSubjects": len(topics),
        "eligibleSubjects": len(eligible),
        "archived": archived_now,
        # every topic (id + title) so the move/delete picker can target any of them,
        # not just the few subjects currently on the board
        "allTopics": [{"id": t["id"], "title": t["title"], "source": t.get("source"),
                       "sessionCount": t["sessionCount"], "lastActivity": t["lastActivity"]}
                      for t in topics],
    }


def _recap_worker():
    """Background daemon: backfill recaps + issue cards, refresh changed ones each loop."""
    while True:
        try:
            n = _recap_refresh()
            if n:
                print(f"[recaps] generated/updated {n} session recap(s)")
        except Exception as e:
            print(f"[recaps] worker error: {e}")
        try:
            m = _issuecard_refresh()
            if m:
                print(f"[issuecards] generated/updated {m} issue card(s)")
        except Exception as e:
            print(f"[issuecards] worker error: {e}")
        time.sleep(RECAP_INTERVAL)


def _build_context():
    now = time.time()
    if _ctx_cache["data"] and now - _ctx_cache["at"] < CACHE_TTL:
        return _ctx_cache["data"]

    # Scan every session log (capped high only as a runaway guard) so counts are
    # accurate. Reading a few hundred small logs is cheap and the result is cached.
    files = sorted(glob.glob(os.path.join(SESS_DIR, "*.jsonl")),
                   key=os.path.getmtime, reverse=True)[:500]
    # sessions whose last activity is older than STALE_DAYS are dropped everywhere
    stale_cut = (datetime.datetime.now(datetime.timezone.utc)
                 - datetime.timedelta(days=STALE_DAYS)).isoformat()
    closed = _closed_load()
    flags = _sflags_load()
    sessions = []
    for f in files:
        sid = os.path.basename(f)[:-6]  # filename stem = sessionId
        if (flags.get(sid) or {}).get("deleted"):
            continue  # soft-deleted -> hidden from both dashboards (log untouched)
        s = _scan_session(f)
        pj = _proj_of(s["cwd"])
        if not pj or not s["ts0"] or s["n"] == 0:
            continue
        if (s["ts1"] or "") < stale_cut:
            continue  # untouched for over a week -> gone from both dashboards
        sessions.append(dict(
            id=sid,
            archivedSelf=bool((flags.get(sid) or {}).get("archived")),
            cwd=s["cwd"], edited=s["edited"],
            project=pj[0], label=pj[1], isRoot=pj[2],
            branch=s["branch"], start=s["ts0"], end=s["ts1"],
            durationMin=_dur_min(s["ts0"], s["ts1"]),
            prompt=(s["first"] or "")[:200],
            lastPrompt=(s["last"] or "")[:200],
            summary=s["summary"], msgs=s["n"],
            ctxTokens=s["ctxTokens"], ctxPeak=s["ctxPeak"],
            ctxWindow=_ctx_window(s["ctxPeak"]),
            ctxPct=min(100, round(s["ctxTokens"] / _ctx_window(s["ctxPeak"]) * 100)),
            ctxPeakPct=min(100, round(s["ctxPeak"] / _ctx_window(s["ctxPeak"]) * 100)),
        ))
    sessions.sort(key=lambda x: x["end"], reverse=True)

    # attach cached AI recaps (the background worker keeps these fresh) + closed flag
    rcache = _recap_load()
    for s in sessions:
        s["recap"] = (rcache.get(s["id"]) or {}).get("recap")
        s["closed"] = s["id"] in closed

    # resolve topics (hybrid fallback chain) across ALL sessions, then overlay manual edits
    _assign_topics(sessions)
    _apply_topic_overrides(sessions)
    topics = {}
    for s in sessions:
        tp = topics.setdefault(s["_key"], dict(
            id=s["_key"], title=s["_title"], source=s["_src"],
            sessionCount=0, lastActivity=s["end"], sessions=[]))
        tp["sessionCount"] += 1
        if s["end"] > tp["lastActivity"]:
            tp["lastActivity"] = s["end"]
        tp["sessions"].append({k: s[k] for k in (
            "id", "project", "label", "branch", "start", "end", "prompt",
            "lastPrompt", "summary", "msgs", "durationMin", "recap", "closed",
            "archivedSelf", "ctxTokens", "ctxPct", "ctxPeak", "ctxPeakPct", "ctxWindow")})
    topic_list = sorted(topics.values(), key=lambda x: x["lastActivity"], reverse=True)

    # archive state: archiving a topic puts the WHOLE topic — and every session in it —
    # into archive mode. Annotate both so the dashboard greys them and sorts them down.
    archived_ids = _archived_topic_ids(topic_list)
    for t in topic_list:
        t["archived"] = t["id"] in archived_ids  # whole-topic archive
        for st in t["sessions"]:
            # a session is archived if its topic is, OR it was archived individually
            st["archived"] = t["archived"] or st.get("archivedSelf", False)
    for s in sessions:
        s["archived"] = (s["_key"] in archived_ids) or s.get("archivedSelf", False)

    # aggregate projects (skip the bare MyProjects root — those are meta chats)
    week_ago = (datetime.datetime.now(datetime.timezone.utc) -
                datetime.timedelta(days=7)).isoformat()
    projects = {}
    for s in sessions:
        if s["isRoot"]:
            continue
        p = projects.setdefault(s["project"], dict(
            name=s["project"], label=s["label"], lastActivity=s["end"],
            firstSeen=s["start"], sessionCount=0, minutes=0, path=s["cwd"],
            lastSessionId=s["id"],
            lastPrompt=s["lastPrompt"] or s["prompt"], bigPicture=s["prompt"]))
        p["sessionCount"] += 1
        p["minutes"] += s["durationMin"]
        if s["end"] > p["lastActivity"]:
            p["lastActivity"] = s["end"]
            p["path"] = s["cwd"]
            p["lastSessionId"] = s["id"]
            p["lastPrompt"] = s["prompt"]  # opening prompt of most-recent session
        if s["start"] < p["firstSeen"]:
            p["firstSeen"] = s["start"]
            p["bigPicture"] = s["prompt"]
    proj_list = sorted(projects.values(), key=lambda x: x["lastActivity"], reverse=True)
    # genuinely most-active project = most sessions (tie-break: most recent)
    most_active = max(
        proj_list,
        key=lambda p: (p["sessionCount"], p["lastActivity"]),
        default=None,
    )

    data = dict(
        generated_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),
        resume=proj_list[0] if proj_list else None,
        projects=proj_list[:4],
        projectCount=len(proj_list),
        mostActive=most_active,
        topics=topic_list,
        sessions=sessions[:8],
        sessionCount=len(sessions),
        sessionsThisWeek=sum(1 for s in sessions if s["end"] >= week_ago),
    )
    _ctx_cache.update(at=now, data=data)
    return data


def _token():
    out = subprocess.check_output(
        ["security", "find-generic-password", "-s", "Claude Code-credentials", "-w"]
    )
    return json.loads(out).get("claudeAiOauth", {}).get("accessToken", "")


def _fetch_usage():
    now = time.time()
    if _cache["data"] and now - _cache["at"] < CACHE_TTL:
        return _cache["data"]
    req = urllib.request.Request(
        USAGE_URL,
        headers={
            "Authorization": f"Bearer {_token()}",
            "anthropic-beta": "oauth-2025-04-20",
            "Content-Type": "application/json",
        },
    )
    # nosec B310 — URL is the hardcoded https USAGE_URL constant, never user input
    with urllib.request.urlopen(req, timeout=15) as r:  # nosec B310
        data = json.loads(r.read())
    _cache.update(at=now, data=data)
    return data


REG_PATH = os.path.join(STATE_DIR, "iterm-registry.json")


def _reg_load():
    try:
        with open(REG_PATH) as fh:
            return json.load(fh)
    except Exception:
        return {}


def _reg_save(reg):
    try:
        with open(REG_PATH, "w") as fh:
            json.dump(reg, fh)
    except Exception:
        pass


def _osa(script):
    # timeout so a busy/unresponsive iTerm (or a pending Automation prompt) can never
    # hang the request thread indefinitely.
    return subprocess.run(["osascript", "-e", script],
                          check=True, capture_output=True, text=True,
                          timeout=20).stdout.strip()


def _is_running(sid):
    """True if this session is currently LIVE — a background agent or an already-attached
    process. `claude --resume` refuses a live session, so we must attach instead of resume.
    Detected by finding a claude process whose command line carries this session id."""
    try:
        r = subprocess.run(["pgrep", "-f", sid], capture_output=True, text=True, timeout=5)
        return bool(r.stdout.strip())
    except Exception:
        return False


def _open_in_iterm(sid, cwd):
    """Focus the iTerm tab already running this session, or open a new one.

    We remember the iTerm session id we created for each Claude session id in a
    small on-disk registry, so we never open a duplicate tab — and it survives a
    restart of this server. Returns "focused" or "opened".
    """
    reg = _reg_load()
    iterm_id = reg.get(sid)

    # 1) if we've opened this session before, try to focus that exact tab
    if iterm_id:
        found = _osa(f'''
        tell application "iTerm2"
          repeat with w in windows
            repeat with t in tabs of w
              repeat with s in sessions of t
                if (id of s) is "{iterm_id}" then
                  select w
                  tell t to select
                  tell s to select
                  activate
                  return "focused"
                end if
              end repeat
            end repeat
          end repeat
          return "notfound"
        end tell''')
        if found == "focused":
            return "focused"

    # 2) session is currently LIVE (background agent / attached elsewhere)? It can't be
    #    --resume'd. Open the agents manager so you can find and attach to it instead.
    if _is_running(sid):
        cmd = f"cd {shlex.quote(cwd)} && claude agents --cwd {shlex.quote(cwd)}"
        _osa(f'''
        tell application "iTerm2"
          activate
          if (count of windows) = 0 then
            set theWin to (create window with default profile)
          else
            set theWin to current window
            tell theWin to create tab with default profile
          end if
          tell current session of theWin to write text {json.dumps(cmd)}
        end tell''')
        return "running"

    # 3) otherwise open a fresh tab (or window) and remember its iTerm id
    cmd = f"cd {shlex.quote(cwd)} && claude --resume {sid} --permission-mode auto"
    new_id = _osa(f'''
    tell application "iTerm2"
      activate
      if (count of windows) = 0 then
        set theWin to (create window with default profile)
      else
        set theWin to current window
        tell theWin to create tab with default profile
      end if
      tell current session of theWin to write text {json.dumps(cmd)}
      return id of current session of theWin
    end tell''')
    if new_id:
        reg[sid] = new_id
        _reg_save(reg)
    return "opened"


def _close_iterm(sid):
    """Close the iTerm tab we opened for this session. We can only close ones we
    launched (tracked in the registry). Returns closed / notfound / unknown."""
    reg = _reg_load()
    iterm_id = reg.get(sid)
    if not iterm_id:
        return "unknown"
    res = _osa(f'''
    tell application "iTerm2"
      repeat with w in windows
        repeat with t in tabs of w
          repeat with s in sessions of t
            if (id of s) is "{iterm_id}" then
              tell s to close
              return "closed"
            end if
          end repeat
        end repeat
      end repeat
      return "notfound"
    end tell''')
    reg.pop(sid, None)
    _reg_save(reg)
    return res or "notfound"


class Handler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **k):
        super().__init__(*a, directory=DIR, **k)

    def end_headers(self):
        # never let the browser cache the dashboard pages/assets — during active dev a
        # stale cached focus.html means clicks run old JS. APIs manage their own headers.
        if not self.path.startswith("/api"):
            self.send_header("Cache-Control", "no-store, must-revalidate")
        super().end_headers()

    def _json(self, obj, code=200):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_POST(self):
        is_open = self.path.startswith("/api/open")
        is_close = self.path.startswith("/api/close")
        if self.path.startswith("/api/refresh"):
            # force a re-scan + regenerate the focus board's issue cards, off-thread
            _ctx_cache["at"] = 0
            threading.Thread(target=_issuecard_refresh, daemon=True).start()
            return self._json({"ok": True, "refreshing": True})
        if self.path.startswith("/api/archive"):
            try:
                length = int(self.headers.get("Content-Length", 0))
                body = json.loads(self.rfile.read(length) or b"{}")
                key = body.get("subject", "")
                if not key:
                    return self._json({"error": "missing subject"}, 400)
                topics = _build_context().get("topics") or []
                archived = set_archived(key, bool(body.get("undo")), topics)
                _ctx_cache["at"] = 0  # so both dashboards show the archive at once
                return self._json({"ok": True, "subject": key, "archived": archived})
            except Exception as e:
                return self._json({"error": str(e)}, 500)
        if self.path.startswith("/api/topic/"):
            try:
                length = int(self.headers.get("Content-Length", 0))
                body = json.loads(self.rfile.read(length) or b"{}")
                action = self.path[len("/api/topic/"):].strip("/")
                result = _topic_action(action, body)
                _ctx_cache["at"] = 0  # so the new grouping shows on the next poll
                return self._json({"ok": True, **result})
            except ValueError as e:
                return self._json({"error": str(e)}, 400)
            except Exception as e:
                return self._json({"error": str(e)}, 500)
        if self.path.startswith("/api/sessions/"):
            try:
                length = int(self.headers.get("Content-Length", 0))
                body = json.loads(self.rfile.read(length) or b"{}")
                action = self.path[len("/api/sessions/"):].strip("/")
                result = _sessions_action(action, body)
                _ctx_cache["at"] = 0
                return self._json({"ok": True, **result})
            except ValueError as e:
                return self._json({"error": str(e)}, 400)
            except Exception as e:
                return self._json({"error": str(e)}, 500)
        if self.path.startswith("/api/read"):
            try:
                length = int(self.headers.get("Content-Length", 0))
                body = json.loads(self.rfile.read(length) or b"{}")
                marks = _load_read()
                items = (body["marks"].items() if isinstance(body.get("marks"), dict)
                         else [(body.get("session", ""), body.get("end", ""))])
                n = 0
                for sid, end in items:
                    if re.fullmatch(r"[0-9a-fA-F-]{36}", sid or "") and end:
                        marks[sid] = end
                        n += 1
                _save_read(marks)
                return self._json({"ok": True, "marked": n})
            except Exception as e:
                return self._json({"error": str(e)}, 500)
        if is_open or is_close:
            try:
                length = int(self.headers.get("Content-Length", 0))
                body = json.loads(self.rfile.read(length) or b"{}")
                sid = body.get("session", "")
                # strict allow-list: a session id is a UUID
                if not re.fullmatch(r"[0-9a-fA-F-]{36}", sid):
                    return self._json({"error": "invalid session id"}, 400)
                if is_close:
                    # close the iTerm tab if we opened it, AND persist the "closed"
                    # mark so the row greys out with status "closed" (undo via reopen)
                    undo = bool(body.get("undo"))
                    action = "reopened" if undo else _close_iterm(sid)
                    closed = set_closed(sid, undo)
                    _ctx_cache["at"] = 0  # so the closed/reopened state shows at once
                    return self._json({"ok": True, "action": action,
                                       "closed": closed, "session": sid})
                # open: recover the session's working directory from its log
                cwd = MP
                path = os.path.join(SESS_DIR, sid + ".jsonl")
                if os.path.exists(path):
                    with open(path, errors="ignore") as fh:
                        for line in fh:
                            try:
                                r = json.loads(line)
                            except Exception:
                                continue
                            if r.get("cwd"):
                                cwd = r["cwd"]
                                break
                action = _open_in_iterm(sid, cwd)
                return self._json({"ok": True, "action": action, "cwd": cwd, "session": sid})
            except subprocess.CalledProcessError as e:
                return self._json({"error": "osascript failed — grant Automation "
                                            "permission to control iTerm", "detail": str(e)}, 500)
            except Exception as e:
                return self._json({"error": str(e)}, 500)
        self._json({"error": "not found"}, 404)

    def do_GET(self):
        # the refocus board is the landing page
        if self.path in ("/", "/index.html"):
            self.send_response(302)
            self.send_header("Location", "/focus.html")
            self.end_headers()
            return
        if self.path.startswith("/api/focus"):
            try:
                self._json(_build_focus())
            except Exception as e:
                self._json({"error": str(e)}, 502)
            return
        if self.path.startswith("/api/context"):
            try:
                self._json(_apply_read_state(_build_context()))
            except Exception as e:
                self._json({"error": str(e)}, 502)
            return
        if self.path.startswith("/api/trash"):
            try:
                self._json(_trash_list())
            except Exception as e:
                self._json({"error": str(e)}, 502)
            return
        if self.path.startswith("/api/usage"):
            try:
                body = json.dumps(_fetch_usage()).encode()
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Cache-Control", "no-store")
            except Exception as e:
                body = json.dumps({"error": str(e)}).encode()
                self.send_response(502)
                self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
            return
        super().do_GET()

    def log_message(self, *a):  # quiet
        pass


if __name__ == "__main__":
    # background recap worker — generates/refreshes session recaps via `claude -p`
    threading.Thread(target=_recap_worker, daemon=True).start()
    # Threaded server: one slow/blocked request (e.g. a hung osascript or usage fetch)
    # must never freeze the whole dashboard. daemon_threads so it shuts down cleanly.
    http.server.ThreadingHTTPServer.allow_reuse_address = True
    http.server.ThreadingHTTPServer.daemon_threads = True
    with http.server.ThreadingHTTPServer(("127.0.0.1", PORT), Handler) as httpd:
        print(f"Dev Dispatch → http://localhost:{PORT}/dev-dispatch.html")
        print(f"[recaps] worker on, every {RECAP_INTERVAL}s via {RECAP_MODEL}")
        httpd.serve_forever()
